version: '3.8'

services:
  api:
    build: .
    container_name: ai-doc-generator-api
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./config.yaml:/app/config.yaml
      - ./logs:/app/logs
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=5000
      - LOG_LEVEL=info
      - UPLOAD_DIR=/app/uploads
      - CORS_ORIGINS=*
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  default:
    name: ai-doc-generator-network
